-- PUBLIC.PATIENT definition

-- Drop table

-- DROP TABLE PUBLIC.PATIENT;

CREATE TABLE PUBLIC.PATIENT
(
    ID   INTEGER               NOT NULL,
    NAME CHARACTER VARYING(60) NOT NULL,
    CONSTRAINT PATIENT_PK PRIMARY KEY (ID)
);